Feature/268 add enums for network config settings
Deltares/ra2ce pull request #269
Opened 2023-11-24 11:39 UTC by ArdtK

2023-11-24 15:11 UTC, Carsopre requested changes

2023-11-24 15:18 UTC, ArdtK commented on ra2ce/graph/network_config_data/network_config_data_validator.py
> +        if enum.name == "INVALID":
The check needs to be done on the base to make it applicable for other enums. The base can't contain enums, which gives an linting error.
Adjusted though.

2023-11-24 15:18 UTC, ArdtK commented on ra2ce/graph/network_config_data/network_config_data_reader.py
> +        _network_section.source = self._get_enum(_section, "source", SourceEnum)
Fair point.

2023-11-24 15:19 UTC, ArdtK commented on tests/test_data/acceptance_test_data/output/network.ini
Correct. Will revert. Done unintentionally.

2023-11-24 15:20 UTC, ArdtK commented on ra2ce/graph/network_config_data/network_config_data_reader.py
> +        self, section_name: str, property: str, enum_type: type(Enum)
This works.

2023-11-27 07:26 UTC, Carsopre commented on ra2ce/graph/network_config_data/network_config_data_reader.py
> +        self, section_name: str, property: str, enum_type: type(Enum)
Right, also something that got updated, however, you need to use the brackets ( `type[Enum]`), not the parenthesis, if that's not allowed, please revert back to `Type`. More info: https://docs.python.org/3/library/typing.html#the-type-of-class-objects

2023-11-27 13:04 UTC, Carsopre requested changes
I'm still unsure about the `NONE` enum, if a list does not contain elements it should just simply be empty.
Aside from this remark, there are other minor ones. Of course TC needs to be green.

2023-11-27 13:04 UTC, Carsopre commented on ra2ce/graph/network_config_data/network_config_data_reader.py
> +                self._parser.getlist(_section, "road_types", fallback=[None]),
The default value should be `[]`?
```suggestion
                self._parser.getlist(_section, "road_types", fallback=[]),
```

2023-11-27 13:23 UTC, ArdtK commented on ra2ce/analyses/analysis_config_data/enums/weighing_enum.py
> +    NONE = 0
Added in Ra2ceEnumBase.

2023-11-27 13:30 UTC, ArdtK commented on ra2ce/analyses/indirect/analyses_indirect.py
> +            if analysis.weighing == WeighingEnum.DISTANCE:
Check

2023-11-27 13:31 UTC, ArdtK commented on ra2ce/configuration/ra2ce_enum_base.py
> +            return True
Agree

2023-11-27 13:31 UTC, ArdtK commented on ra2ce/graph/network_config_data/enums/aggregate_wl_enum.py
> +    NONE = 0
Explained

2023-11-27 13:32 UTC, ArdtK commented on ra2ce/graph/network_config_data/enums/road_type_enum.py
> +    RESIDENTIAL = 12
Chose 98

2023-11-27 13:33 UTC, ArdtK commented on ra2ce/graph/network_config_data/network_config_data.py
> +    road_types: list[RoadTypeEnum] = field(default_factory=lambda: [RoadTypeEnum.NONE])
Adjusted

2023-11-27 13:33 UTC, ArdtK commented on ra2ce/graph/network_config_data/network_config_data_reader.py
> +                self._parser.getlist(_section, "road_types", fallback=[None]),
Adjusted

2023-11-27 13:40 UTC, Carsopre approved these changes
Approved although the parsing of the `weighing_enum.py` can be improved so to reduce its defined enums.

2023-11-27 15:12 UTC, merged