Feature/144 network cleaning simplifying functions
Deltares/ra2ce pull request #322
Opened 2024-03-12 12:06 UTC by ArdtK

2024-04-09 07:20 UTC, Carsopre requested changes
@sahand-asgarpour at this moment I see too many functions which are a copy & paste (or variations) from the `osmnx` library. I believe it is a better approach to just have a `osmnx_custom_library.py` file with such methods so that it is more traceable. Keep in mind that I do not support this approach as it can bring us more dependencies as it was demonstrated on #410 .

On the other hand, you should be able to start writing small (pytests) tests to verify the functionalities being written.

2024-04-09 07:20 UTC, Carsopre commented on ra2ce/network/network_wrappers/osm_network_wrapper/osm_utils.py
> +    utils.log(f"Found nearest edge ({u, v, data, key}) to node {node}")
do not log with a third party library, instead do:
```python
import logging
...
logging.info(f"Found nearest edge...")
```

2024-04-09 07:20 UTC, Carsopre commented on ra2ce/network/network_wrappers/osm_network_wrapper/osm_utils.py
> +def _is_endnode_simplified(graph: MultiDiGraph, node: int) -> bool:
This method should not be with  underscore `_`. This symbol represents that the method is private and should only be accessed by methods within the same context, however you are importing it from another module. 

Please do not forget to describe the docstrings.

2024-04-09 07:20 UTC, Carsopre commented on ra2ce/network/network_wrappers/osm_network_wrapper/osm_utils.py
> +
What do you do if none of the above conditions is met? Do not forget to add a default return statement.

2024-04-09 07:20 UTC, Carsopre commented on ra2ce/network/network_wrappers/osm_network_wrapper/osm_utils.py
> +def remove_key(element_data: dict, keys_to_exclude: list):
Output type hints + docstrings please.

2024-04-09 07:20 UTC, Carsopre commented on ra2ce/network/network_wrappers/osm_network_wrapper/osm_utils.py
> +def find_existing_node(graph: MultiDiGraph, new_node: Point) -> Union[Tuple[int, dict], Tuple[None, None]]:
Docstrings please.

2024-04-09 07:20 UTC, Carsopre commented on ra2ce/network/network_wrappers/osm_network_wrapper/osm_utils.py
> +
Docstrings please.

2024-04-09 12:27 UTC, sahand-asgarpour commented
> @sahand-asgarpour at this moment I see too many functions which are a copy & paste (or variations) from the `osmnx` library. I believe it is a better approach to just have a `osmnx_custom_library.py` file with such methods so that it is more traceable. Keep in mind that I do not support this approach as it can bring us more dependencies as it was demonstrated on #410 .
> 
> On the other hand, you should be able to start writing small (pytests) tests to verify the functionalities being written.

2024-04-10 15:49 UTC, Carsopre approved these changes

2024-04-10 15:50 UTC, merged