326 create unittests for a simplified case
Deltares/ra2ce pull request #344
Opened 2024-03-14 14:03 UTC by MatthiasHauthDeltares

2024-03-14 15:38 UTC, Carsopre requested changes
Some remarks must be processed before merging.

2024-03-14 15:38 UTC, Carsopre commented on ra2ce/analysis/indirect/losses.py
> +        sep: str = ",",
don't add default values please, make explicit calls instead.

2024-03-14 15:38 UTC, Carsopre commented on tests/analysis/indirect/test_losses.py
> +            name="single_link_redundancy_losses_test",
Make your life easier:

```suggestion
        _losses_csv_data = test_data.joinpath("losses", "losses", "csv_data_for_losses")
        _analyses = AnalysisSectionIndirect(
            part_of_day=None,
            resilience_curve_file=_losses_csv_data.joinpath("resilience_curve.csv"),
            traffic_intensities_file=_losses_csv_data.joinpath("traffic_intensities.csv"),
            values_of_time_file=_losses_csv_data.joinpath("values_of_time.csv"),
            name="single_link_redundancy_losses_test",
```

2024-03-14 15:38 UTC, Carsopre commented on tests/analysis/indirect/test_losses.py
> +        _config.config_data.input_path = test_data / "losses" / "csv_data_for_losses"
Same as before.

2024-03-15 07:42 UTC, MatthiasHauthDeltares commented on ra2ce/analysis/indirect/losses.py
> +        sep: str = ",",
done

2024-03-15 09:38 UTC, Carsopre approved these changes

2024-03-15 09:38 UTC, merged