Doc/test multi link losses
Deltares/ra2ce pull request #411
Opened 2024-04-05 15:39 UTC by sahand-asgarpour

## Issue addressed
Solves #<issue number>

## What has been done?
Adapting the single_link_losses for the multi_link_losses using multi_link_redundancy

## Checklist
- [ ] Tests are either added or updated.
- [ ] Branch is up to date with `master`.
- [ ] Updated documentation if needed.

2024-04-10 16:08 UTC, Carsopre requested changes
Just a small remark regarding usage of enums.

2024-04-10 16:08 UTC, Carsopre commented on ra2ce/analysis/indirect/losses.py
Apply suggestions together with the corresponding import:
```python
from ra2ce.analysis.analysis_config_data.enums.analysis_indirect_enum import AnalysisIndirectEnum
```

2024-04-11 06:08 UTC, sahand-asgarpour commented
> .

Thanks! Done.

2024-04-11 07:27 UTC, Carsopre approved these changes

2024-04-11 07:28 UTC, merged