431 losses module results are not correct
Deltares/ra2ce pull request #432
Opened 2024-04-20 19:26 UTC by sahand-asgarpour

## Issue addressed
Solves #431

## Code of conduct
- [ ] I HAVE NOT added sensitive or compromised (test) data to the repository.
- [ ] I HAVE NOT added vulnerabilities to the repository.
- [ ] I HAVE discussed my solution with (other) members of the RA2CE team.

## What has been done?
Explain how you addressed the resolution of the related issue, what choices you made and why.

### Checklist
- [ ] Code is formatted using our custom `black` and `isort` definitions.
- [ ] Tests are either added or updated.
- [ ] Branch is up to date with `master`.
- [ ] Updated documentation if needed.

## Additional Notes (optional)
Add any additional notes or information that may be helpful.

2024-04-22 08:24 UTC, sahand-asgarpour commented
When running test "tests.test_ra2ce_handler.TestRa2ceHandler.test_configure_handler_created_from_config_does_not_raise(Valid network config-Valid analysis config)" locally, I receive no error. But the test failed in TC.

2024-04-22 13:22 UTC, Carsopre requested changes
Some remarks need to be processed, we can have a look afterwards to the failing test.

2024-04-22 13:22 UTC, Carsopre commented on ra2ce/.idea/ra2ce.iml
Please remove this file from version control.

2024-04-22 13:22 UTC, Carsopre commented on ra2ce/analysis/indirect/losses.py
> +                criticality_analysis["EV1_ma"] > float(self.analysis.threshold)
`threshold` is already a `float`. I would not expect this casting to be needed. Please remove.

2024-04-22 13:51 UTC, sahand-asgarpour commented
> Some remarks need to be processed, we can have a look afterwards to the failing test.

Remarks resolved.

2024-05-13 06:42 UTC, Carsopre approved these changes
Minor remarks, you may merge afterwards :)

2024-05-13 06:42 UTC, Carsopre commented on ra2ce/analysis/indirect/losses.py
> +            divisor = 100
For simple `if-else` statements like this you can simply do this to improve readability.
```suggestion
        divisor = 100
        if all(ratio <= 1 for ratio_tuple in relevant_curve["functionality_loss_ratio"] for ratio in ratio_tuple):
                    divisor = 1
```

2024-05-13 06:42 UTC, Carsopre commented on ra2ce/analysis/indirect/losses.py
> +                    elif (not(math.isnan(row_performance_change) and math.isnan(row_connectivity)) and
watch out when you start concatenating so many `if-else` statements with rather complex comparisons.

2024-05-13 06:42 UTC, Carsopre commented on ra2ce/analysis/indirect/multi_link_redundancy.py
> +    def _update_time(self, gdf_calculated: pd.DataFrame, gdf_graph: gpd.GeoDataFrame) -> tuple:
`tuple` of what?

2024-05-13 06:42 UTC, Carsopre commented on ra2ce/analysis/indirect/multi_link_redundancy.py
> +    def _update_time(self, gdf_calculated: pd.DataFrame, gdf_graph: gpd.GeoDataFrame) -> tuple:
Perhaps `tuple[pd.Dataframe, gpd.GeoDataFrame]` ?

2024-05-14 11:49 UTC, merged