Feat/449 adjust analysis config data
Deltares/ra2ce pull request #450
Opened 2024-05-28 10:58 UTC by ArdtK

## Issue addressed
Solves #449

## Code of conduct
- [ ] I HAVE NOT added sensitive or compromised (test) data to the repository.
- [ ] I HAVE NOT added vulnerabilities to the repository.
- [ ] I HAVE discussed my solution with (other) members of the RA2CE team.

## What has been done?
Rename direct/indirect into damages/losses in subpackage `analysis\analysis_config_data`
* Rename all enums and analysis section classes
* Refactor all modules/examples using these classes
* Rename entry `DIRECT` into `DIRECT_DAMAGE` in `AnalysisDamagesEnum`
  * Merge directory `direct` into `direct_damage` in `test_data`

### Checklist
- [ ] Code is formatted using our custom `black` and `isort` definitions.
- [ ] Tests are either added or updated.
- [ ] Branch is up to date with `master`.
- [ ] Updated documentation if needed.

## Additional Notes (optional)
N.A.

2024-05-28 19:13 UTC, Carsopre requested changes
I think we should be consistent on the use of a plural / singular word. If a class / property is in plural, then a collection of them should be `properties_collection` or `properties_list`.
Confusing whatsoever.

2024-05-29 11:51 UTC, Carsopre commented on ra2ce/analysis/analysis_config_data/analysis_config_data.py
>      )
```suggestion
    analysis: Banana= field(
        default_factory=lambda: AnalysisLossesEnum.INVALID
    )
```

2024-05-30 08:27 UTC, ArdtK commented on ra2ce/analysis/analysis_config_data/analysis_config_data.py
> +class AnalysisSectionLosses(AnalysisSectionBase):
Agreed that it will be plural

2024-05-30 09:27 UTC, Carsopre approved these changes

2024-05-30 09:30 UTC, merged