Feat/485 further improvements avg speed
Deltares/ra2ce pull request #486
Opened 2024-06-20 15:26 UTC by ArdtK

## Issue addressed
Solves #<issue number>

## Code of conduct
- [ ] I HAVE NOT added sensitive or compromised (test) data to the repository.
- [ ] I HAVE NOT added vulnerabilities to the repository.
- [ ] I HAVE discussed my solution with (other) members of the RA2CE team.

## What has been done?
Explain how you addressed the resolution of the related issue, what choices you made and why.

### Checklist
- [ ] Code is formatted using our custom `black` and `isort` definitions.
- [ ] Tests are either added or updated.
- [ ] Branch is up to date with `master`.
- [ ] Updated documentation if needed.

## Additional Notes (optional)
Add any additional notes or information that may be helpful.

2024-06-25 18:37 UTC, Carsopre requested changes
In general no extraordinary remarks, yet I do not  understand the functionality or the tests from `length_weighing_analysis.extend_graph`.

2024-06-26 06:34 UTC, ArdtK commented on tests/network/avg_speed/test_avg_speed_reader.py
> +        _expected_values = avg_speed_data
Agree

2024-06-26 06:36 UTC, ArdtK commented on tests/network/avg_speed/conftest.py
> +        ([RoadTypeEnum.TERTIARY, RoadTypeEnum.SECONDARY], 7.8),
Done

2024-06-26 06:38 UTC, ArdtK commented on tests/analysis/losses/weighing_analysis/test_time_weighing_analysis.py
> +        valid_analysis.extend_graph(_graph_dict)
Actually, this is your code I restored ;-). In general I agree.

2024-06-26 06:38 UTC, ArdtK commented on tests/analysis/losses/weighing_analysis/test_length_weighing_analysis.py
> +        assert _graph_dict["my_value"] == 42
See previous remark.

2024-06-26 06:39 UTC, ArdtK commented on ra2ce/analysis/losses/weighing_analysis/weighing_analysis_protocol.py
> +        """
Let's have a chat on the weighing calculator in general.

2024-06-26 06:39 UTC, ArdtK commented on ra2ce/analysis/losses/weighing_analysis/length_weighing_analysis.py
> +        return
Same comment

2024-06-26 06:44 UTC, merged