Fix/573 update rfid c in the graph simple after segmentation
Deltares/ra2ce pull request #574
Opened 2024-09-07 22:25 UTC by sahand-asgarpour

## Issue addressed
Solves #573 

## Code of conduct
- [ ] I HAVE NOT added sensitive or compromised (test) data to the repository.
- [ ] I HAVE NOT added vulnerabilities to the repository.
- [ ] I HAVE discussed my solution with (other) members of the RA2CE team.

## What has been done?
Explain how you addressed the resolution of the related issue, what choices you made and why.

### Checklist
- [ ] Code is formatted using our custom `black` and `isort` definitions.
- [ ] Tests are either added or updated.
- [ ] Branch is up to date with `master`.
- [ ] Updated documentation if needed.

## Additional Notes (optional)
Add any additional notes or information that may be helpful.

2024-09-09 10:56 UTC, Carsopre requested changes
Some remarks.
1. The operator `=` does not imply a copy of an object.
2. Do not write inline comments.

2024-09-10 06:22 UTC, sahand-asgarpour commented on ra2ce/network/networks_utils.py
> +    complex_ids_per_simple_id = obtained_simple_ids  # start with a copy
Right, I will use copy() then.

2024-09-10 06:34 UTC, sahand-asgarpour commented
> Some remarks.
> 
>     1. The operator `=` does not imply a copy of an object.
> 
>     2. Do not write inline comments.

Thanks for the review. Remarks addressed.

2024-09-10 07:12 UTC, Carsopre approved these changes

2024-09-10 08:09 UTC, merged