feat: 660 create an example to run damages and losses without input files
Deltares/ra2ce pull request #661
Opened 2024-12-13 09:53 UTC by ArdtK

## Issue addressed
Solves #<issue number>

## Code of conduct
- [ ] I HAVE NOT added sensitive or compromised (test) data to the repository.
- [ ] I HAVE NOT added vulnerabilities to the repository.
- [ ] I HAVE discussed my solution with (other) members of the RA2CE team.

## What has been done?
Explain how you addressed the resolution of the related issue, what choices you made and why.

### Checklist
- [ ] Code is formatted using our custom `black` and `isort` definitions.
- [ ] Tests are either added or updated.
- [ ] Branch is up to date with `master`.
- [ ] Updated documentation if needed.

## Additional Notes (optional)
Add any additional notes or information that may be helpful.

2025-01-08 14:47 UTC, MatthiasHauthDeltares commented
This is a really nice start!
A few observations/comments:

- I find it difficult to figure out what are the keys in the dictionaries made of Enum:
```python

list(_resilience_curves.resilience_curves.keys())[0]
```
returns the key: `(<RoadTypeEnum.SECONDARY: 7>, (0.0, 0.2))`, 
This comment is also valid for `_values_of_time` and `_traffic_intensities`

- For the damage curve:
```python
_manual_damage_functions.damage_functions["all_road_types"].damage_fraction.data
```
This should probably only contains the data as a numpy array instead of a weird dataframe with 2 rows for the title.
Same comment for  `_manual_damage_functions.damage_functions["all_road_types"].max_damage`

2025-01-08 15:17 UTC, ArdtK commented
@MatthiasHauthDeltares the keys of `_resilience_curves` are a composite (tupe) of a link_type (enum) and a hazard intensity range (list[float]).
For `_values_of_time` and `_traffic_intensities` it is quite straighforward, isn't it.

Regarding your comment on the damage function, it returns an interpolator.

We could discuss how to improve/clarify this.

@sahand-asgarpour FYI

2025-01-09 09:49 UTC, Carsopre requested changes
There are some remarks that need attention, specially behavioral changes to the `analysis_runner_factory.py`.

2025-01-09 09:49 UTC, Carsopre commented on examples/tech_meetings/20241213_run_damages_losses_without_files.ipynb
> +    "    hazard_map=[Path(file) for file in hazard_path.glob(\"*.tif\")],\n",
As far as I know you do not need to cast them into `Path` as they are already a subpath from `hazard_path`. https://docs.python.org/3/library/pathlib.html#basic-use

2025-01-09 09:49 UTC, Carsopre commented on ra2ce/analysis/analysis_collection.py
> +            return None
Technically you need to change the type hint, as we now do not guarantee the creation of the object.

2025-01-09 09:49 UTC, Carsopre commented on ra2ce/analysis/analysis_collection.py
> +    ) -> AnalysisLossesProtocol | AnalysisDamagesProtocol | Adaptation:
Simplify?
```suggestion
    ) -> AnalysisProtocol | Adaptation:
```

2025-01-09 09:49 UTC, Carsopre commented on ra2ce/analysis/losses/losses_base.py
> +        # self._check_validity_analysis_files()
Remove?

2025-01-09 09:49 UTC, Carsopre commented on ra2ce/runners/analysis_runner_factory.py
> +    ) -> list[AnalysisResultWrapper]:
Why have you changed the signature of this method? I disagree on this approach, in fact, I do not understand based on the changes why `ra2ce_input` is now needed. If you proceed with this approach `.get_supported_runners` should be modified so that it consumes `analysis_collection`.

The whole purpose of this factory is that the user only needs to define the `ra2ce_input`.

2025-01-09 13:23 UTC, ArdtK commented on ra2ce/runners/analysis_runner_factory.py
> +    ) -> list[AnalysisResultWrapper]:
I don't understand your comment. `ra2ce_input` was already part of the signature. It is needed to know which analysis can be run.
The change that has been done is adding the `analysis_collection` to it, as that allows users to provide the proper inputs to the analyses before running it, as was the goal of this story.
In the current setup `analysis_collection` doesn't contain the info needed, e.g. `ra2ce_input.network_config.config_data.hazard.hazard_map` as checked in `DamagesAnalysisRunner.can_run`.

2025-01-09 13:28 UTC, ArdtK commented on ra2ce/analysis/losses/losses_base.py
> +        # self._check_validity_analysis_files()
Moved to execute, as suggested in the TODO

2025-01-09 13:29 UTC, ArdtK commented on ra2ce/analysis/analysis_collection.py
> +    ) -> AnalysisLossesProtocol | AnalysisDamagesProtocol | Adaptation:
Adjusted, leaving out `Adaptation` as that also implements `AnalysisProtocol`.

2025-01-09 13:30 UTC, ArdtK commented on ra2ce/analysis/analysis_collection.py
> +            return None
Fair point. Adjusted

2025-01-09 15:01 UTC, ArdtK commented on ra2ce/runners/analysis_runner_factory.py
> +    ) -> list[AnalysisResultWrapper]:
I see your point a bit better, after having a closer look at the code. If we can somehow rule out the check on hazard_map in DamagesAnalysisRunner.can_run, we can remove the whole can_run, as in fact this check is already done when creating the analysis_collection.
Perhaps we can move the check on hazard_map to the configure step.

The AnalysisRunnerFactory can then be simplified as we can just use all available runners. In case filter_supported_analyses will give no results (no analysis for that runner present in the collection), it will not execute anything.

One step beyond, we could even get rid of the separate runners, as they don't differ anymore (except having a str which is not used, it seems). The SimpleRunnerBase could become the only runner, just executing all analyses present in the collection.

2025-01-10 07:59 UTC, Carsopre commented on ra2ce/runners/analysis_runner_factory.py
> +    ) -> list[AnalysisResultWrapper]:
Thanks for taking a bit to re(read) my comment. I'd rather discuss with you over this (and in the future hopefully we discuss it prior to implementation).

2025-01-20 13:26 UTC, ArdtK commented on ra2ce/runners/analysis_runner_factory.py
> +    ) -> list[AnalysisResultWrapper]:
Solved in a separate PR and now merged into this branch.

2025-01-20 14:36 UTC, Carsopre approved these changes

2025-01-20 14:36 UTC, merged